### ISSUE TITLE
Set up React testing library

### ISSUE THREAD

**Issue by faraakhatTW** [Impactworkers/iw-complaint-manager#11]
### User Story
As a developer
I want to set up a React testing library for our project
So that I can facilitate comprehensive unit and integration testing of React components

### Definition of Done
- RTL is installed with any necessary config
- Is configured to work properly with Vitest
- A sample test exists using RTL that passes when running the tests

### Acceptance Criteria
**Given** RTL is installed
**When** I run the tests
**Then** a sample test passes

**Comment by CwoodsTW** [comment]
Wasn't necessary but I added vitest/ui with react testing library.  It opens a UI within a browser window to follow the progress and interact with your tests.  Again, not necessary so we can uninstall.
