### ISSUE TITLE
Set up Storybook

### ISSUE THREAD

**Issue by faraakhatTW** [Impactworkers/iw-complaint-manager#13]
### User Story
As a developer
I want to set up storybook in our project
So that I can facilitate component-driven development, improve collaboration, and streamline UI testing

### Definition of Done
- Storybook is installed with proper config in the `iw-complaint-manager` repo.
   - Make sure it is it's own "module" by creating a `iw-storybook` folder in the root of `iw-complaint-manager`
   - The folder structure should be:
      ```
      .
      └── iw-complaint-manager/
          └── *iw-storybook/
              └── package.json
      
      *This will eventually be moved out into its own repo, but for the sake of easy importing we'll build it as a monorepo
      ```

- It's set up to work with MUI
- Autodocs functionality is implemented
- A sample story is visible

### Resources:
[Install for React + Vite](https://storybook.js.org/docs/get-started/react-vite)
[Setup](https://storybook.js.org/docs/get-started/setup)
[Integrate MUI + Storybook](https://storybook.js.org/recipes/@mui/material)
[How to write a story in Typescript](https://storybook.js.org/docs/writing-stories/typescript)
[Implementing Automatic Documentation](https://storybook.js.org/docs/writing-docs/autodocs)

### Acceptance Criteria
**Given** Storybook has been installed and set up
**When** I run `npm run storybook`
**Then** it successfully launches a local dev server for Storybook.

**Given** Storybook is running locally
**When** I view the page
**Then** it shows a sample Storybook story

- [x] Intsall MUI 
- [x] Install Storybook 
- [x] Add configs for Vite and Remix to work properly with Storybook 
- [x] Add custom theming from MUI 
- [x] Add autodoc functionality 
- [x] should be able to run yarn run storybook

**Comment by paul-thompson1** [comment]
Fara and I managed to get custom theming to work with storybook. Here is an example of a button that uses Material UI.

Here is the light theme:
![Screenshot 2024-05-22 at 3 17 56 PM (2)](https://github.com/Impactworkers/iw-complaint-manager/assets/159827724/e70c3557-9425-466b-bbbe-7d61f14b1f47)

And the dark theme:
![Screenshot 2024-05-22 at 3 25 24 PM (2)](https://github.com/Impactworkers/iw-complaint-manager/assets/159827724/057008da-a486-4e44-a871-7dda64174daa)
