### ISSUE TITLE
Set up QA, Staging and Prod environments

### ISSUE THREAD

**Issue by faraakhatTW** [Impactworkers/iw-complaint-manager#15]
### User Story
As a developer
I want to set up a QA, Staging and Prod environment
So that I can ensure thorough testing, seamless deployment, and reliable software delivery

### Definition of Done
- QA, Staging, and Prod envs are setup in the `Impactworkers` Heroku team
   - `iwcm-qa`, `iwcm-staging`, `iwcm-prod`
- 3 new stages exist for the envs in CircleCi config
- Each stage is a manual approval (so the only auto deploy is to `iwcm-dev`)

### Acceptance Criteria
**Given** these environment exist in CircleCi config
**When** I push code up
**Then** only `iwcm-dev` gets deployed to automatically
**AND** QA, Staging, and Prod show "thumbs up" for manual approval
**AND** I can't push to a later environment before the previous environment is deployed to

**Comment by faraakhatTW** [comment]
@arihu1008 commented: 
CircleCI dashboard currently shows `dev`, `qa`, `staging`, `prod` in  consecutive order with manual approval. 
Changed the `dev` application name to `iwcm-dev` to match with other applications.

_We need permission on CircleCI to add environment variables_

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/91972819/ac2360e3-fc7b-47ac-81cb-78f9a923ddc3)

**Comment by arihu1008** [comment]
Environment variables are added in CircleCI. Look below for current pipeline. `qa`, `staging`, and `prod` require approval to deploy.

![Screenshot 2024-05-10 at 3 26 42 PM](https://github.com/Impactworkers/iw-complaint-manager/assets/91972819/f4003986-52fe-49a6-945e-bfb8779eeba1)
