### ISSUE TITLE
Set up CircleCI pipeline

### ISSUE THREAD

**Issue by faraakhatTW** [Impactworkers/iw-complaint-manager#17]
### User Story
As a developer
I want to set up a CircleCI pipeline
So that I can automate the testing and deployment process for my project

### Definition of Done
- CircleCi org `Impactworkers` exists
- Project named `iw-complaint-manager` exists
- CircleCi basic config exists in the repo

### Acceptance Criteria
**Given** I have set up CircleCi
**When** I push changes to `iw-complaint-manager`
**Then** the CircleCi pipeline gets triggered
**AND** the app gets deployed to `cm-dev`

**Comment by faraakhatTW** [comment]
@devonivory Commented:

![Image](https://github.com/PublicDataWorks/complaint-manager/assets/71669240/697c3a57-bcc5-478c-9184-cb23c80b28ad)

The current work is on hold for deploy because there are some dependencies that are required in order to proceed. There isn't any code to be tested for deployment at the moment.

**Comment by justin-c-anthony** [comment]
## Questions for Kickoff

### Deployment Details

What does the cm-dev environment consist of? (e.g., is it a cloud environment, specific server, or containerized environment?)

Are there any specific deployment tools or services being used (e.g., Kubernetes, Docker, AWS, etc.)?

### Environment Variables and Secrets

What environment variables or secrets are required for the build, test, and deployment processes?

How are these secrets managed and accessed securely?

### Testing Requirements

Are there any specific tests that need to be run as part of the CI pipeline?

Are there any code quality or security checks that need to be included?

### Pipeline Structure

Is there a preferred structure for the CircleCI configuration file (e.g., specific jobs, workflows)?

Are there any conditional steps or stages that need to be included in the pipeline?

### Notification Preferences

Are there any notification preferences for build and deployment statuses (e.g., Slack notifications, email alerts)?
