### ISSUE TITLE
Use Remix to initialize project (frontend)

### ISSUE THREAD

**Issue by faraakhatTW** [Impactworkers/iw-complaint-manager#18]
### User Story
As a developer
I want to use Remix to bootstrap a TypeScript-based React project and configure a Yarn workspace
So that I can streamline project setup, enhance development performance, and enable efficient code compilation and bundling

### Definition of Done
- Initialize the typescript react + node project with Remix
- Set up a [yarn workspace](https://yarnpkg.com/features/workspaces)
   - We'll use this to share libraries between complaint manager and our component library
- *Verify Node 20 is our node version*
- Remix config is setup according to best practices
   - [Remix Setup](https://remix.run/docs/en/main/start/quickstart)

### Acceptance Criteria
**Given** Remix is setup
**When** I run the development server
**Then** I'm able to see the error-free default app on localhost

**Comment by rnair-tw** [comment]
this work only covers front-end work, another card needs to be created for back-end work
