### ISSUE TITLE
Set up Figma plugin

### ISSUE THREAD

**Issue by justin-c-anthony** [Impactworkers/iw-complaint-manager#22]
### User Story
As a developer
I want to explore how the Figma token plugin integrates with Storybook
So that I can efficiently manage design tokens and ensure design consistency in our project

### Business Context
In order to keep design and development a lot more consistent, we want to set up a simple [Storybook](https://storybook.js.org/) and test out using the [Figma Tokens plugin](https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens) that can automatically push any design changes directly from Figma. On the dev side, these changes can be pulled by the developer and automatically updated in the project files site wide.

Tutorial on how to do this: https://matthewrea.com/blog/design-token-automation-from-figma-to-storybook/?ref=storybookblog.ghost.io

### In Scope
1. Ensure that Storybook is set up and running in the project environment
2. Install the Figma token plugin in Figma
3. ~~Integrate the Figma token plugin with Storybook~~
4. Verify that the plugin can access design tokens from the Figma file
5. ~~Create or select a component in Storybook~~
6. Apply design tokens (such as colors, typography, spacing) using the Figma token plugin
7. ~~Ensure that the component styling reflects the changes made with the plugin~~

## Acceptance Criteria

1. Scenario: 
Given I have successfully integrated the Figma token plugin with ~~Storybook~~ Github
~~And selected a component in Storybook~~
When I apply design tokens using the Figma token plugin (change the color)
~~Then the component styling reflects the changes made with the plugin (color is changed to the same color)~~
Then I can push the changes to Github

2. Scenario:
Given the `tokens.json` file has been updated and added to the main branch of our repo
When a developer pulls the changes
Then they can run a script to convert the `token.json` file to a `.js` file (which can later be used with MUI)

### Notes
https://storybook.js.org/addons/@storybook/addon-designs/

**Comment by justin-c-anthony** [comment]
From Reshmi 2.29:

turn this into a story

**Comment by arihu1008** [comment]
We tripled with @rowsnr and tested Figspec. When a change is made in Figma, Storybook components reflects the change. However, when we set the parameter in Storybook component, part of the url copied over from Figma needs to be changed from 'design' to 'file'.

**Comment by paul-thompson1** [comment]
Here is an example Storybook component that uses Storybook Addons which presents the Figma file. The Storybook component was made with MUI.

![Image](https://github.com/Impactworkers/iw-complaint-manager/assets/159827724/76e93053-0902-4356-913e-7a3ee71a04f8)

**Comment by mariliasoaresTW** [comment]
Options:

1. Use storybook designs addons (fig spec or sigma feature) - is not working
2. Use Design Tokens Figma plugin (Sync with GitHub)
3. Do what’s listed on the card - complex and time consuming
4. Karhan - Using Token Studio plugin

**Comment by arihu1008** [comment]
Figspec was working until earlier today, but can't see the design of the figma component in the Storybook after an edit has been made in Figma. Reaching out to Robert Sullivan(referred by Karhan) for insights on syncing token studio and Storybook.

**Comment by paul-thompson1** [comment]
Sent the email to Robert. Going to perform additional research into design tokens plugin (Token Studio). Will followup with Robert tomorrow.

**Comment by paul-thompson1** [comment]
Did extensive research into Tokens Studio and tested it out on my personal github and personal figma profile. Just to understand what to expect before implementation in this repo. Basically you just need to create a fine-grained token and include it in the settings for token studio. Afterwards Token Studio will be able to send the tokens json file after the initial commit. Also researched style-dictionary. Will followup with Robert via google chat after standup. Found a potential way to save money with Figma.

My proposal for saving money is to have the impactworkers email have access to figma and figma dev mode. That way we don't have to pay 25 USD for each person who needs Figma dev mode. We can use 1password for the figma credentials.

**Comment by paul-thompson1** [comment]
Worked on Figma Token Studio plugin. Used an example tokens.json file and transformed the tokens.json into js and scss files. We were able to import a variable from the variables.js file into storybook and defined the background color of the button as black. We also heard from Robert. He will look for some resources regarding integrating storybook and design tokens. Tomorrow, we will setup the fine-grained token to be used with Figma Token Studio. So we can push the tokens.json file to GitHub. Also plan to develop a script to build the transformed variable files. 

Note: We used style-dictionary and sd-transforms packages to transform the tokens.json file.

Resources used: 
- https://configurator.tokens.studio/
- https://github.com/amzn/style-dictionary/blob/main/examples/advanced/custom-transforms/build.js
- https://github.com/amzn/style-dictionary/blob/main/examples/advanced/custom-transforms/config.json
- https://classic.yarnpkg.com/en/package/@tokens-studio/sd-transforms

**Comment by paul-thompson1** [comment]
Got the design tokens json file synced to GitHub. Need to use [tokens-studio/sd-tranforms](https://github.com/tokens-studio/sd-transforms) and [style-dictionary](https://github.com/amzn/style-dictionary) to be able to transform and convert the design tokens to SCSS. Met with Robert on Friday. Recommended to meet with another person. Asked for help in NA Beach per Shak's instructions, but I have yet to receive a response. 

Robert used custom themes and cloned angular material ui website to create documentation for their components. We could create a custom theme for material UI and interface the theme with Storybook. 

![Image](https://github.com/Impactworkers/iw-complaint-manager/assets/159827724/65354c64-abd5-45c6-85bc-136df3547021)

**Comment by paul-thompson1** [comment]
## How did the meeting with Robert go?
- Met with Robert on Friday. Robert was able to create a custom theme with scss and mirror the angular themes website in order to create custom documentation for their component library. He did not use Storybook.

## How is the Figma design tokens JSON file created?

- The Figma Design Tokens json file is created by pushing to the main GitHub branch within the Figma plugin. Setup is done through a GitHub personal access token.

## How do I convert the design tokens JSON file to SCSS?

- Once created, you must run the build file in order to transform the design tokens json file to aa scss file. 

## How do I integrate the custom SCSS with Storybook? 

- We can create a custom MUI theme in order to customize the MUI components. We can interface the MUI theme with Storybook. 

## Anything else worth mentioning?
- Instead of having multiple developer's access Figma through their own separate Figma accounts. Which is 25 dollars per person. We could just use the impactworkers email to have access to Figma and sync the credentials through 1password. That way if someone rolls off the project we don't have to worry about removing their personal access token. Also it will save us money to not have to pay for multiple Figma Accounts.

**Comment by rd-huerta** [comment]
### To do:
- [ ] Update the acceptance criteria on card #22
- [ ] Create github token for Natalia
- [ ] Create new card for integrating with MUI

**Comment by rd-huerta** [comment]
@paul-thompson1 and I created a new document in our wiki called [Working with Figma Plugin for Designers](https://impactworkers.github.io/iw-complaint-manager/how-to/working-with-figma#working-with-figma-plugin-for-designers). We will meet with @rowsnr tomorrow to go over the documentation and walk through creating the Github token.
