### ISSUE TITLE
Set up versioning

### ISSUE THREAD

**Issue by justin-c-anthony** [Impactworkers/iw-complaint-manager#27]
### User Story
As a developer
I want to set up versioning for our project
So that we can track changes, manage releases, and ensure transparency and clarity in our development process

### Definition of Done
- Setup [release-please](https://github.com/googleapis/release-please) library
- Create a doc in v2 wiki (or update existing doc) to explain how to use it (similar to how we use `.versionrc` in v1)
- Hook it up with circleci to bump the version when pushing to `iwcm-staging`

### Acceptance Criteria
**Given** release-please is setup and configured
**When** I commit using one of the keywords (e.g. feat)
**Then** the changelog is updated accordingly

**Given** release-please is setup and configured
**When** I deploy to `iwcm-staging`
**Then** the version is bumped

**Comment by rd-huerta** [comment]
### What work has been done
- We have been spiking on the recommended way(using Github Actions) to set up release-please in our repository
  - we created a `release-please.yml` workflow 
  - we created a personal access token and configured it with the appropriate permissions necessary for the `release-please.yml` workflow. 
  - successfully created and ran the workflow in the Github Actions tab
  - release please created a [pull request](https://github.com/Impactworkers/iw-complaint-manager/pull/65) in our repo

### What work still needs to be done
- create the `CHANGELOG.md' file
- understand how release-please is handling the version-bump

### Questions
1. How should we handle personal access tokens(PAT)? For example, when a developer leaves the team, their PAT will no longer work in the github actions workflow. 
2.

**Comment by rd-huerta** [comment]
Understanding the PR
- the label `autorelease: pending` means the PR has not been merged
- in the `autorelease: pending` state, additional work is added to the PR
- when you are ready to create a release, merge the PR
  - the `changelog.md` and `package.json`  files will be merged with main, triggering the CircleCI pipeline to run again
    - The artifact can be promoted to staging? 
    - Tagging will be done manually by merging the PR in github

**Comment by rd-huerta** [comment]
### To do
- [ ] look into adding a `create release` step in the pipeline that can merge the PR before deploying to the staging environment
- [ ] setup PAT using a machine user
- [ ] Once the work is completed, make sure team is on the same page about conventional commit messages

**Comment by rd-huerta** [comment]
### Questions to be discussed at future code retro or team meeting:
- What constitutes a major breaking change?
  - What is our strategy for bumping the version numbers?
        - When in doubt, bump the patch
        - During the initial dev phase start the release at 0.1.0 and bump the minor version for each subsequent release
- Who is the audience for the changelog?
  - This will influence what we want to add to the changelog, i.e., devs vs. clients
