### ISSUE TITLE
Fix CircleCI Pipeline

### ISSUE THREAD

**Issue by rd-huerta** [Impactworkers/iw-complaint-manager#72]
### User Story
As a developer
I want to fix the CircleCI pipeline
So that we can deploy to higher environments

### Resources
1. [Configure a Node.js application on CircleCI](https://circleci.com/docs/language-javascript/#overview)
2. [Continuous deployment for Next.js applications to Heroku](https://circleci.com/blog/continuous-deployment-for-next-js-apps/)
3. [Storing Build Artifacts](https://circleci.com/docs/artifacts/#artifacts-optimization)
4. [Artifacts documentation](https://circleci.com/docs/persist-data/#artifacts) 
5. [Custom Storage Usage](https://circleci.com/docs/persist-data/#custom-storage-usage)
### Questions
1. Do we store release artifacts anywhere? 
2. If we want to store the build artifact and pass it between jobs in the CircleCI pipeline, how long should we store it for? There are potential cost implications. Our free plan gives us 2GB of storage/month. Currently we are using 83.2MB. 
### Definition of Done
What means that this task is done?

### Acceptance Criteria
**Given** xxxx
**When** xxxx
**Then** xxxx

**Comment by CwoodsTW** [comment]
Currently looking at documentation about artifacts and workspaces to see which is better to use when passing the build between jobs/environments in the pipeline. 
https://circleci.com/docs/workspaces/
https://circleci.com/docs/artifacts/

**Comment by CwoodsTW** [comment]
Questions : What would be an optimal amount of time to save previous workspaces(Max 15 days).

**Comment by CwoodsTW** [comment]
I believe we may currently be blocked.  We are using workspaces in circle-ci and have added a logging job to see the files attached to the workspace in dev environment.  However, the QA environment is still not receiving the workspace.  The QA environment on circle-ci is still un clickable as well so debugging has been a bit of a chore.

**Comment by rd-huerta** [comment]
Deploying to higher environments is now working in the pipeline. Woohoo! Great job team!
